# Generated by Django 4.0.4 on 2023-01-07 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('contact', models.IntegerField(max_length=8)),
                ('adresse', models.CharField(max_length=200)),
                ('dateCreation', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Distributeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('contact', models.IntegerField(max_length=8)),
                ('adresse', models.CharField(max_length=200)),
                ('dateCreation', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Distributeur',
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='ProvisionEau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField(max_length=4)),
                ('date_prov', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Commmande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_sachet', models.PositiveIntegerField()),
                ('date_com', models.DateField(auto_now_add=True)),
                ('montant', models.FloatField(blank=True)),
                ('date_appro', models.DateField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.client')),
                ('distributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.distributeur')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='distributeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.distributeur'),
        ),
    ]
