# Generated by Django 4.1.4 on 2023-03-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_client_latitude_client_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='commandeStatut',
            field=models.CharField(choices=[('E', 'En attente'), ('L', 'Livrer')], default='E', max_length=1, verbose_name='rôle'),
        ),
    ]
