# Generated by Django 4.0.4 on 2023-01-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_alter_distributeur_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributeur',
            name='contact',
            field=models.CharField(max_length=11),
        ),
    ]
