# Generated by Django 4.0.4 on 2023-02-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_produit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='name',
            new_name='nom',
        ),
    ]
