# Generated by Django 4.0.4 on 2023-01-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_alter_distributeur_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisioneau',
            name='code',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
