# Generated by Django 4.1.4 on 2023-02-11 20:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('water', '0003_rename_name_produit_nom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commmande',
            new_name='Commande',
        ),
    ]
