# Generated by Django 4.1.4 on 2023-02-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_rename_commmande_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_appro',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='montant',
            field=models.FloatField(null=True),
        ),
    ]
