# Generated by Django 4.0.4 on 2023-01-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0005_remove_provisioneau_code_provisioneau_distributeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisioneau',
            name='code',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
