# Generated by Django 4.0.4 on 2023-01-18 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0006_provisioneau_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisioneau',
            name='distributeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='water.distributeur'),
        ),
    ]
