# Generated by Django 4.0.4 on 2023-02-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
